services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8085:80
    volumes:
      - .htaccess:/var/www/html/.htaccess
    restart: always
    environment:
      - WORDPRESS_DB_HOST=192.168.1.2
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
