pipeline {

    agent any

    stages {

        stage("Verify tooling") {
            steps {
                sh '''
              cd wordpress
              docker version
              docker info
              docker compose version
              curl --version
              jq --version
              docker compose ps
            '''
            }
        }

        stage("Build and re-start docker compose services") {
            environment {
                WORDPRESS_DB_PASSWORD = credentials('WORDPRESS_DB_PASSWORD')
            }
            steps {
                sh '''
                 cd wordpress
                 docker compose build --build-arg WORDPRESS_DB_PASSWORD='$WORDPRESS_DB_PASSWORD'
                 docker compose up -d 
              '''
            }
        }
    }
}
